### ISSUE TITLE
update appreciated

### ISSUE THREAD

**Issue by eccccco** [pixeltris/TwitchAdBlock#12]
I got some problems with ublock (cannot use their current version). Therefore I would be very thankful if you could update TwitchAdBlock.
I'd guess I'm not the only one who doesn't rely on uBlock  entirely.

**Comment by pixeltris** [comment]
I wrote some info on the new twitch ad changes here https://github.com/pixeltris/TwitchAdBlock/issues/11. I don't think there is any reason for updating this repo as the same changes can be done with uBlock. If there is some other use case I'll look into updating this repo otherwise I'll leave it as is and make any pull requests if necessary to uBlock instead.
